### ISSUE TITLE
TOANSWER: still open research questions

### ISSUE THREAD

**Issue by darosior** [revault/watchtower_paper#7]
- [x] Coin creation, see #5 
- [x]  Coin selection, see #6 
- [x] Coin allocation, see #12 
- [x] When to feebump
   - ~~Are we happy with my pulled-off interval function?~~
   - Jacob to comment on #3 
- [x] Refilling
   - Do we agree that we just send funds to the watchtower wallet and it figures out how to use them?
- [x] Fee reserve, see #10
- [x] Given a formal model of our fee-reserve system, can we simulate/ extrapolate the dynamics, and test various edge-cases, to verify that it stays sane? And what is the cost of re-calibrating over time with changing fee-market conditions?
- [x]  How to notice and exploit the low-fee periods?
